# Generated by Django 5.0.2 on 2024-02-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_plan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskplan',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_plan.category'),
        ),
    ]
